name: Deploy Portfolio

on:
  push:
    branches:
      - main  # deploys whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./project  # add if your package.json is inside "project" folder

      - name: Build Vite project
        run: npm run build
        working-directory: ./project  # same as above

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./project/dist  # Vite's build output

